# Generated by Django 2.2.1 on 2019-06-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190606_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhours',
            options={'verbose_name_plural': 'TeraBhai'},
        ),
    ]
