# Generated by Django 2.2.1 on 2019-06-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190607_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='iin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='workhours',
            options={'verbose_name_plural': 'WorkHour'},
        ),
    ]
