# Generated by Django 2.2.1 on 2019-06-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190611_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iin',
        ),
    ]
