# Generated by Django 2.2.2 on 2019-06-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_e'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhours',
            options={},
        ),
    ]
