# Generated by Django 2.2.2 on 2019-07-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190617_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
    ]
